name: Publish Elixir Package to Hex

on:
  push:
    branches:
      - master # Trigger only on pushes to the master branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: actions/checkout@v3
      

    - name: Install Dependencies
      run: mix deps.get

    - name: Publish to Hex
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
        mix hex.publish --yes
